language: node_js
node_js:
- '6'
script: npm run build
deploy:
  provider: s3
  region: $S3_REGION
  bucket: $S3_BUCKET
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  acl: public_read
  local_dir: build
  detect_encoding: true
  skip_cleanup: true
cache:
  bundler: true
  directories:
    - node_modules